apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - family-growth-external-secret.yaml
  - mongo-deployment.yaml
  - gateway-deployment.yaml
  - user-service-deployment.yaml
  - progress-service-deployment.yaml
  - homework-service-deployment.yaml
  - clamav-deployment.yaml
  - clamav-service.yaml
  - clamav-network-policy.yaml
  - resource-service-deployment.yaml
  - analytics-service-deployment.yaml
  - notification-service-deployment.yaml
